# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScoreScanner/ScoreScannerWithPyQt/src/Home.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 531)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(186, 199, 208);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_SSL = QtWidgets.QLabel(self.centralwidget)
        self.label_SSL.setGeometry(QtCore.QRect(0, 0, 211, 71))
        self.label_SSL.setStyleSheet("background-color: rgb(105, 105, 105);")
        self.label_SSL.setObjectName("label_SSL")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.label_logo.setStyleSheet("border-image: url(:/Icons/logo.png);\n"
"background-color: rgb(105, 105, 105);")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.label_ScoreScanner = QtWidgets.QLabel(self.centralwidget)
        self.label_ScoreScanner.setGeometry(QtCore.QRect(70, 10, 111, 51))
        self.label_ScoreScanner.setStyleSheet("background-color: rgb(105, 105, 105);")
        self.label_ScoreScanner.setObjectName("label_ScoreScanner")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 70, 211, 409))
        self.listView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.boton_Usuario = QtWidgets.QPushButton(self.centralwidget)
        self.boton_Usuario.setGeometry(QtCore.QRect(50, 120, 61, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.boton_Usuario.setFont(font)
        self.boton_Usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;")
        self.boton_Usuario.setObjectName("boton_Usuario")
        self.label_Dashboard = QtWidgets.QLabel(self.centralwidget)
        self.label_Dashboard.setGeometry(QtCore.QRect(40, 100, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Dashboard.setFont(font)
        self.label_Dashboard.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Dashboard.setObjectName("label_Dashboard")
        self.label_Partituras = QtWidgets.QLabel(self.centralwidget)
        self.label_Partituras.setGeometry(QtCore.QRect(40, 180, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Partituras.setFont(font)
        self.label_Partituras.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Partituras.setObjectName("label_Partituras")
        self.boton_RegistroP = QtWidgets.QPushButton(self.centralwidget)
        self.boton_RegistroP.setGeometry(QtCore.QRect(50, 200, 141, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.boton_RegistroP.setFont(font)
        self.boton_RegistroP.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;")
        self.boton_RegistroP.setObjectName("boton_RegistroP")
        self.boton_GestorP = QtWidgets.QPushButton(self.centralwidget)
        self.boton_GestorP.setGeometry(QtCore.QRect(50, 230, 131, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.boton_GestorP.setFont(font)
        self.boton_GestorP.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;")
        self.boton_GestorP.setObjectName("boton_GestorP")
        self.label_Extras = QtWidgets.QLabel(self.centralwidget)
        self.label_Extras.setGeometry(QtCore.QRect(40, 310, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Extras.setFont(font)
        self.label_Extras.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Extras.setObjectName("label_Extras")
        self.boton_AboutUs = QtWidgets.QPushButton(self.centralwidget)
        self.boton_AboutUs.setGeometry(QtCore.QRect(50, 330, 61, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.boton_AboutUs.setFont(font)
        self.boton_AboutUs.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;")
        self.boton_AboutUs.setObjectName("boton_AboutUs")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 0, 531, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.listView.raise_()
        self.label_SSL.raise_()
        self.label_logo.raise_()
        self.label_ScoreScanner.raise_()
        self.boton_Usuario.raise_()
        self.label_Dashboard.raise_()
        self.label_Partituras.raise_()
        self.boton_RegistroP.raise_()
        self.boton_GestorP.raise_()
        self.label_Extras.raise_()
        self.boton_AboutUs.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_SSL.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_ScoreScanner.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Score</span><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Scanner </span></p></body></html>"))
        self.boton_Usuario.setText(_translate("MainWindow", "Usuario"))
        self.label_Dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.label_Partituras.setText(_translate("MainWindow", "Parituras"))
        self.boton_RegistroP.setText(_translate("MainWindow", "Registro de partituras"))
        self.boton_GestorP.setText(_translate("MainWindow", "Gestor de partituras"))
        self.label_Extras.setText(_translate("MainWindow", "Extras"))
        self.boton_AboutUs.setText(_translate("MainWindow", "About us"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt;\">@Username</span></p></body></html>"))

import logo_rc
